Fix Large Object Handler Memory Issue
leo-project/leo_gateway pull request #62
Opened 2017-01-10 07:42 UTC by windkit

## Description
Switch to rpc:call and gen_server:call with {timeout, infinity}

## Related Issue
https://github.com/leo-project/leofs/issues/570

2017-01-11 02:37 UTC, mocchira requested changes

2017-01-11 02:37 UTC, mocchira commented on src/leo_gateway_rpc_handler.erl
> +            ?warn("invoke/5", [{error, Error}]),
This may cause logging burst problem when clients try to access a file that doesn't exist as I previously mentioned at another issue.
as you know,  handle_error already has produced warning in case badrpc and unknown one and
IIRC the caller leo_gateway_s3_api logged in case unavailable so removing this line looks good to me.

2017-01-11 03:44 UTC, windkit commented on src/leo_gateway_rpc_handler.erl
> +            ?warn("invoke/5", [{error, Error}]),
thanks for you comment, I have updated the PR

2017-01-11 04:08 UTC, mocchira approved these changes

2017-01-12 02:04 UTC, merged

2017-01-12 02:04 UTC, yosukehara commented
@windkit Reviewed and merged, thanks.